[package]
name = "chatbot"
version = "0.2.3"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "MIT"
description = "An extensible chatbot"
documentation = "https://chatbot.rs/chatbot/"
repository = "https://github.com/jwilm/chatbot"
keywords = ["chat", "bot", "extensible"]
readme = "README.md"

[dependencies]
abort_on_panic = "1.0.0"
regex = "0.1"
rustc-serialize = "0.3"
getopts = "0.2"
irc = { version = "0.11", optional = true }
slack =  { git = "https://github.com/jwilm/slack-rs", rev = "async-sender", optional = true }

[features]
default = []
irc-adapter = ["irc"]
slack-adapter = ["slack"]
