[package]
name = "chatbot"
version = "0.2.0"
authors = ["Joe Wilm <jdwilm@gmail.com>"]
license = "MIT"
description = "An extensible chatbot"
documentation = "https://chatbot.rs/chatbot/"
repository = "https://github.com/jwilm/chatbot"
keywords = ["chat", "bot", "extensible"]
readme = "README.md"

[[bin]]
doc = false
name = "chatbot"
path = "src/main.rs"

[dependencies]
regex = "0.1.30"
hyper = "0.5.0"
rustc-serialize = "0.3.14"
slack = "0.6.0"
getopts = "0.2"
irc = "0.8.14"
